[package]
name = "dx_todo_frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "^0.22.1"
chrono = { version = "^0.4.38", features = ["serde"] }
console_error_panic_hook = "^0.1.7"
futures = "^0.3.30"
leptos = { version = "^0.6.12", features = ["csr", "nightly"] }
progenitor = "^0.7.0"
rand = "^0.8.5"
reqwest = { version = "^0.12.4", features = ["json", "stream"] }
serde = { version = "^1.0.203", features = ["derive"] }
uuid = { version = "^1.0.0", features = ["serde", "v4", "v7"] }
