[workspace]
resolver = "2"
members = ["server"]

[package]
name = "dx_todo_frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hot-lib-reloader = { version = "^0.7.0", optional = true }
server = { path = "server", default-features = false }
dotenvy = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "signal"] }
tracing = { workspace = true }
dxp-logging = { workspace = true, optional = true, default-features = false }

[workspace.dependencies]
poem = { version = "^3.0.1" }
poem-grants = { version ="^3.0.0" }
dotenvy = { version = "^0.15.7" }
tokio = { version = "^1.37.0", default-features = false }
anyhow = { version = "^1.0.86", features = ["backtrace"] }
dxp-dbsession = { git = "https://github.com/887/dxp-dbsession.git", default-features = true }
sea-orm = { version = "^0.12.15", default-features = false }
dbopen = { path = "dbopen", default-features = false }
tracing-subscriber = { version = "^0.3.18", features = ["env-filter"] }
tracing = "^0.1.40"
tracing-appender = { version = "^0.2.3" }
serde = { version = "^1.0.203", features = ["derive"] }
dxp-logging = { git = "https://github.com/887/dxp-logging.git", default-features = false }

[features]
default = ["sqlite-rustls", "log", "hot-reload"]
hot-reload = ["dep:hot-lib-reloader", "server/hot-reload"]
mysql-rustls = ["server/mysql-rustls"]
mysql-native-tls = ["server/mysql-native-tls"]
sqlite-rustls = ["server/sqlite-rustls"]
sqlite-native-tls = ["server/sqlite-native-tls"]
postgres-rustls = ["server/postgres-rustls"]
postgres-native-tls = ["server/postgres-native-tls"]
log=["dep:dxp-logging", "dxp-logging/log", "server/log"]
log-file=["log", "dxp-logging/log-file", "server/log-file"]
