name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build css-builder
      working-directory: "server/tools/css-builder"
      run: cargo build --release --verbose

    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose

    - name: Run tests
      run: cargo test --verbose
